### ISSUE TITLE
Even with uploadNewFilesOnly: false, doesn't always update files

### ISSUE THREAD

**Issue by toddmedema** [clineamb/gulp-s3-upload#10]
Need an option that force-uploads files, even if they don't "look" like they've changed - sometimes a file will get corrupted while uploading, and the only way to fix it right now is to manually log in to the server and delete it.

For what it's worth, the process where it checks to see if it should update the file also dramatically increases the time it takes to upload because of the extra server call.

[12:25:48] Uploading ..... todd/low/1/sled_arrow.png
[12:25:49] Updated ....... todd/low/1/sled_arrow.png
[12:25:49] Uploading ..... todd/med/1/ad.css
[12:25:50] No Change ..... todd/med/1/ad.css
[12:25:50] Uploading ..... todd/med/1/ad.html
[12:25:51] No Change ..... todd/med/1/ad.html

**Comment by clineamb** [comment]
We do the s3.headObject call as a less-intensive server call.  While, yes, this does create a bit of overhead, I preferred seeing the data if a file needed o be changed or not instead of blindly assuming they all upload and overwrote.

I personally haven't had an explicit case of a file getting corrupted, could essentially make a slight change to a file to make sure it gets seen to be uploaded (for now).

I'll add the option sometime beginning of next week to force upload all the time (as I'm away this weekend).

**Comment by toddmedema** [comment]
Thank you, much appreciated!

**Comment by clineamb** [comment]
I started to dig into this feature today.  Remembering how this is done (now that I'm looking at the source), the plugin still makes a `putObject` call, so your file is always being uploaded.  We just do a `headObject` call to compare the data (if it's the same, it's changed; if not, it's new to the bucket).

Essentially this is already forcing the upload and overwriting.  I'll be adding the option to skip the extra messaging, but we're already forcing the upload.

Now, if you (and others) think force-emptying the bucket and then uploading the files to be 100% brand-spankin' new to the bucket is valuable, we can create a new feature thread for that as a TODO.

**Comment by toddmedema** [comment]
Ah, interesting! We've definitely had issues with the current system not during a full overwrite (perhaps because it keeps the header info from the old files or something?)

So maybe there's three modes? The current mode (check but still overwrite all), fast (check and only overwrite changes) and nuclear (upload from clean slate)?

**Comment by clineamb** [comment]
So that middle mode is probably not possible, because the plugin does a check against the "ETag" which changes if the data changes.  

The flow is such:

*  [s3.headObject](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property) call; returns `data1`.
    *  (You can see what this data is in the docs that I linked)
* [s3.putObject](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property) call; returns `data2`
  *  According to [AWS SDK .NET docs](http://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/M_Amazon_S3_AmazonS3Client_PutObject.htm), this is an overwrite if it exists. Also, only the .NET docs have the "Remarks" section that I mention, so ignore the language difference, I imagine AWS' call on their end works the same no matter the language.
* If `data1.ETag` === `data2.ETag`, then the file is unchanged; otherwise, it's new. (The .NET docs reference I made notes this.)

This is why the "current mode" works as such to send back to the CLI information about your upload.  The "fast mode" would essentially just skip the `s3.headObject` call, reducing overhead, but you might still get the same issues, since the overwriting happens at the `s3.putObject` call.

For the "nuclear" mode, we can make a [deleteObject](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#deleteObject-property) call, but we'd still need to make the `s3.headObject` call to check that an object actually exists.

Our calls would end up being such (nuclear mode would actually add a third call):

* current mode -- `s3.headObject`, `s3.putObject`
* fast mode -- `s3.putObject`
* nuclear mode -- `s3.headObject`, `s3.deleteObject`, `s3.putObject`


My only guess for your issues can either be connectivity (once or twice that this has happened to me has been over a bad connection) or something on AWS/S3's end.  There also could be a stream issue in the gulp pipe which I may not be taking into account.

**Comment by toddmedema** [comment]
Makes sense! The Internet is a finicky beast, always gotta assume that something'll go wrong somewhere :)

**Comment by clineamb** [comment]
I will still consider adding, perhaps, nuclear mode in a later version (maybe w/ the multi-threaded featured from the other thread you submitted #11) .

For now, I'll close this.

Thanks for the input!
