### ISSUE TITLE
Can't have locally deleted files to be deleted in S3

### ISSUE THREAD

**Issue by lucas-nadalutti** [clineamb/gulp-s3-upload#20]
I noticed that renamed/deleted files aren't deleted in my S3 bucket. Is this the expected behavior?

Thanks in advance!

**Comment by clineamb** [comment]
Yes, this is indeed expected behavior of the current version.  This is a strict upload task (currently) and does not mirror.  The plugin does not detect for name changes, since changing the name of an object creates a whole new ETag (hash of the file), since it is indeed a change to said file.

This can be added as a feature, though I think it might be better served a as a separate task plugin.
