### ISSUE TITLE
stops at 16 files

### ISSUE THREAD

**Issue by michaelerobertsjr** [clineamb/gulp-s3-upload#3]
I am testing out your plugin, but it seems to stop at the first 16 files that I include as source files.

Is there any limit to the size or number of files that it can handle?

**Comment by clineamb** [comment]
While working on the upgrade to v1, I've begun to run into a stopping problem now (13 files on average, but in random order).

**Comment by clineamb** [comment]
What seemed to be happening was the callback was prematurely ending the uploads since we return the file in the callback.  Removing the file param from the through stream callback solved this problem for me consistently.  

Commit message w/ fix was the wrong commit, but where I made the change is here: b61918e11dc3957a000fb150b3b8a68763395871
